### PR TITLE
Detect BC breaks

### PR DESCRIPTION
**Pull request by OndraM**
Via https://github.com/Roave/BackwardCompatibilityCheck .

Also fixed some missing dependencies (which must be properly defined to make BackwardCompatibilityCheck work properly).

Danger should report BC breaks to the PR.

### CODE REVIEW

**Comment by danger-lmc** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Backward incompatible changes introduced by this PR
  </td>
    </tr>
  </tbody>
</table>




## Backward incompatible changes detected
 - [BC] The parameter $messageFactory of Lmc\Matej\Http\RequestManager#setMessageFactory() changed from Http\Message\MessageFactory to a non-contravariant Http\Discovery\MessageFactoryDiscovery
 - [BC] The parameter $messageFactory of Lmc\Matej\Http\RequestManager#setMessageFactory() changed from Http\Message\MessageFactory to Http\Discovery\MessageFactoryDiscovery


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by OndraM** [comment]
Example of failed build is in #76 :

fail

**Comment by foglcz** [comment]
:heart_eyes: :+1:

**Review by foglcz — APPROVED** [review]

**Review by MortalFlesh — APPROVED** [review]

**Review by legendik — APPROVED** [review]

**Pull request merged**
